#!/usr/bin/env bash
#
# export.sh - dump the project's git-tracked text files into a single file for
# pasting into an LLM chat as context.
#
# Output goes to docs/llm/dump.txt. That directory is git-ignored (see
# .gitignore) so the dump is never committed and is excluded from release zips.
#
# What it does:
#   * enumerates git-tracked files only (nothing ignored, nothing untracked);
#   * skips this script's own output directory (docs/llm/) and a few noisy
#     paths (the verbatim LICENSE text, lock files);
#   * skips anything that looks like a binary file;
#   * writes each file preceded by a header giving its repo-relative path.
#
# Usage:
#   ./export.sh            # writes docs/llm/dump.txt
#   ./export.sh out.txt    # writes to a custom path instead
#
set -euo pipefail

# Move to the repository root so relative paths are stable regardless of the
# directory the script is invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

OUT="${1:-docs/llm/dump.txt}"

# Paths (repo-relative) to leave out of the dump. These are either enormous and
# uninteresting for LLM context (the license text) or generated (lock files).
EXCLUDES=(
  "docs/llm/"
  "LICENSE"
  "Cargo.lock"
)

is_excluded() {
  local path="$1" prefix
  for prefix in "${EXCLUDES[@]}"; do
    case "$path" in
      "$prefix"*) return 0 ;;
    esac
  done
  return 1
}

mkdir -p "$(dirname "$OUT")"
: > "$OUT" # truncate / create

{
  printf '# myinkbird source dump\n'
  printf '# generated by export.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '# tracked files only; docs/llm/, LICENSE and lock files omitted\n\n'
} >> "$OUT"

count=0
# -z / read -d '' keeps paths with spaces or newlines intact.
while IFS= read -r -d '' path; do
  is_excluded "$path" && continue
  # Skip binary files: grep -I reports "binary file matches" and returns
  # non-zero via -q when the file is binary.
  if ! grep -Iq . "$path" 2>/dev/null; then
    continue
  fi
  {
    printf '========================================================================\n'
    printf 'FILE: %s\n' "$path"
    printf '========================================================================\n'
    cat "$path"
    printf '\n'
  } >> "$OUT"
  count=$((count + 1))
done < <(git ls-files -z)

printf 'export.sh: wrote %d files to %s\n' "$count" "$OUT" >&2
